/* This file was generated by the Caitlin compiler. Do not edit manually. */
package io.github.strangepleasures.caitlin.stdlib;

import static io.github.strangepleasures.caitlin.stdlib.StdLib.*;

public final class StdLib {

    public static void println(String s) {
        System.out.println(s);
    }

    public static void println(Object o) {
        System.out.println(o);
    }
}
