package io.github.strangepleasures.caitlin.compiler;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.visitor.ModifierVisitor;
import com.github.javaparser.ast.visitor.Visitable;

import static com.github.javaparser.StaticJavaParser.parseImport;

class HeaderPostprocessor extends ModifierVisitor<Void> {
    @Override
    public Visitable visit(CompilationUnit n, Void arg) {
        n.setBlockComment(" This file was generated by the Caitlin compiler. Do not edit manually. ");
        if (!n.getPackageDeclaration().map(pd -> pd.getName().getIdentifier()).orElse("").startsWith("io.github.strangepleasures.caitlin.stdlib.")) {
            n.getImports().addFirst(parseImport("import static io.github.strangepleasures.caitlin.stdlib.StdLib.*;"));
        }
        return n;
    }
}
