/* This file was generated by the Caitlin compiler. Do not edit manually. */
package com.example;

import static io.github.strangepleasures.caitlin.stdlib.StdLib.*;

class Hello {

    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
